package com.blueventor.network.response


data class ResponseDriverDetails(
    val data: List<Data>,  // <-- change to List<Data>
    val message: String,
    val status: Int
) {
    data class Data(
        val account_balance: String,
        val address: String,
        val booking_limit: Int,
        val cancel_trips_count: String,
        val city_name: String,
        val company_address: String,
        val company_id: Int,
        val company_name: String,
        val company_userid: Int,
        val completed_trips_count: String,
        val country_code: String,
        val country_name: String,
        val current_trip: List<Any>,
        val device_type: String,
        val driver_code: String,
        val driver_insurance_expire_date: String,
        val driver_insurance_number: String,
        val driver_licence: String,
        val driver_licence_back_side: String,
        val driver_license_expire_date: String,
        val driver_license_id: String,
        val driver_status: String,
        val driver_type: String,
        val email: String,
        val gender: String,
        val id: Int,
        val lastname: String,
        val login_status: String,
        val mapping_enddate: String,
        val mapping_startdate: String,
        val max_luggage: Int,
        val model_id: Int,
        val model_name: String,
        val name: String,
        val oustation_availability: Int,
        val phone: String,
        val profile_picture: String,
        val recharge_limit: Int,
        val rental_availability: Int,
        val shift_status: String,
        val last_location_updated: String,
        val signup_status: Int,
        val state_name: String,
        val status: String,
        val taxi_colour: String,
        val taxi_fc_expiry_date: String,
        val taxi_image: String,
        val taxi_insurance_expire_date_time: String,
        val taxi_insurance_number: String,
        val taxi_manufacturer: String,
        val taxi_manufacturing_year: String,
        val taxi_min_speed: String,
        val taxi_motor_expire_date: String,
        val taxi_no: String,
        val taxi_owner_name: String,
        val taxi_permit_expiry_date: String,
        val today_login_hours: String,
        val total_trips_count: String,
        val user_type: String,
        val today_earnings: String,
        val last_location_name: String,
        val vehicle_registration_license: String
    )
}
